export {default as INPUT}           from "./INPUT"
export {default as SELECT}		    from "./SELECT"
export {default as RSELECT}         from "./REACT_SELECT"
export {default as TEXTAREA}	    from "./TEXTAREA"
export {default as CHECKBOX}        from "./CHECKBOX"
export {default as FILE}            from "./FILE"